# This workflow configures GitHub Actions to run Flutter commands on each push or PR.
# You can adapt or extend it for your own needs (e.g., multiple platforms, build steps).

name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Sets up Flutter on the specified version (or 'stable' channel).
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Use the Flutter version matching your 'sdk' in pubspec.yaml if desired.
          # Alternatively, specify 'stable' or a pinned version, e.g. '3.6.0'.
          flutter-version: "stable"

      - name: Install dependencies
        run: flutter pub get

      # Optional: uncomment if you want to enforce code formatting on each commit.
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
